### ISSUE TITLE
csv 文件处理错误

### ISSUE THREAD

**Issue by Pana** [conflux-fans/TokenBatchSender#10]
<img width="842" alt="Screen Shot 2021-05-20 at 11 16 08 AM" src="https://user-images.githubusercontent.com/552081/118913866-d7961880-b95c-11eb-9ec6-fd932f026f97.png">

[bulk-send.csv](https://github.com/conflux-fans/TokenBatchSender/files/6512616/bulk-send.csv)

**Comment by Pana** [comment]
该文件上传后处理出错

**Comment by Pana** [comment]
因为该文件最后多了一个空行。csv 处理的鲁棒性需要兼容一下

**Comment by darwintree** [comment]
已处理，现在遇到空行会跳过
