### ISSUE TITLE
csv 文件行数过多，报错

### ISSUE THREAD

**Issue by Pana** [conflux-fans/TokenBatchSender#11]
[example (3).csv](https://github.com/conflux-fans/TokenBatchSender/files/6512711/example.3.csv)

行数过多，前端解析会报错。
测试 200 条可以成功解析。

csv 解析失败的时候，在页面给出一个提示比较友好

**Comment by darwintree** [comment]
已处理。该bug的可能触发原因是调用的高精度库`number-precision`接口`NP.plus(...arr)`在参数过多时报错栈溢出。现在改变了调用的方式。

不过在上传较大文件时页面的响应会慢一拍，可能是上传文件或渲染数据带来的副作用，暂时没找到有效的解决办法。作为补偿的办法，现在在页面中加入了对应的文字提示

**Comment by wangdayong228** [comment]
问题不大，读取速度可以接受
