### ISSUE TITLE
CSV错误需要一次性解析完成

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/TokenBatchSender#12]
如下，最后两行的地址格式都不对，现在只报告`cfxtest:aap1r1sa29wst7vukjz8257zs0rmsfax6pxygpp74a`,需要两行错误都报告
```
cfxtest:aapyctkv4ck1yv1ymw94ypfg1fv25nm05jruyewche, 1
cfxtest:aap1r1sa29wst7vukjz8257zs0rmsfax6pxygpp74s, 0.000000001
cfxtest:aap1r1sa29wst7vukjz8257zs0rmsfax6pxygpp74a, 0.00002
cfxtest:aap1r1sa29wst7vukjz8257zs0rmsfax6pxygpp74b, 0.00002
```

**Comment by darwintree** [comment]
已解决。调整了处理csv每行的流程。

**Comment by wangdayong228** [comment]
需要说明详情，address错误还是value错误及错误原因
![image](https://user-images.githubusercontent.com/11971608/119473469-c5adde80-bd7d-11eb-8704-7c9bc136843b.png)
