### ISSUE TITLE
网络切换时 invalid base32 address

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/TokenBatchSender#13]
复现步骤
1. 切主网
2. 代币选择"测试Token GLD"
3. 报错 "invalid base32 address"

**Comment by darwintree** [comment]
现在主网中只能选择主网合约，测试网中只能选择测试网合约。

**Comment by wangdayong228** [comment]
下拉列表通过配置文件完成，切换网络后根据配置文件更新下拉列表，不支持的token不需要显示；
