### ISSUE TITLE
"请连接钱包"和"请选择Token"两个提示信息需要分开

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/TokenBatchSender#15]
- 未连接钱包时，提示 "请连接钱包"
- 已连接钱包但为选择代币时，提示"请选择Token"

![image](https://user-images.githubusercontent.com/11971608/119079086-01694100-ba2a-11eb-909a-71f0782ad915.png)

**Comment by darwintree** [comment]
已解决
