### ISSUE TITLE
没有安装portal时提示用户安装，参考moonswap

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/TokenBatchSender#19]
没有安装portal时提示用户安装，参考moonswap
![image](https://user-images.githubusercontent.com/11971608/119483948-1c201a80-bd88-11eb-9e3b-2ef643a8d83d.png)

**Comment by wangdayong228** [comment]
未安装portal时 ，点”连接钱包“也提示安装portal
![image](https://user-images.githubusercontent.com/11971608/119763591-6b7a5e00-bee2-11eb-85e7-880274ed9b55.png)

**Comment by darwintree** [comment]
已修改。现在在未安装portal时，弹窗无法关闭。用户无法在未安装Portal时与页面进行交互
