### ISSUE TITLE
考虑小数位数

### ISSUE THREAD

**Issue by wangdayong228** [conflux-fans/TokenBatchSender#20]
- 由于token可能存在小数位非18位的情况，前端需要根据合约小数位数计算实际发送的value值。
- 用户输入小数位数超出合约decimals，报错
- UI 展示decimals，可以的话做成像下面这样，然后我们多一列余额

![image](https://user-images.githubusercontent.com/11971608/119764255-a630c600-bee3-11eb-9df1-c104ae3277d4.png)

**Comment by darwintree** [comment]
Decimals相关功能已实现。
但ERC777 Token标准中约定ERC 777 标准的Token 中 decimals 为可选的实现项，而且如果实现，则必须将该值设为18。
见https://eips.ethereum.org/EIPS/eip-777#backward-compatibility
> The token MAY implement decimals() for backward compatibility with ERC-20. If implemented, it MUST always return 18.

**Comment by wangdayong228** [comment]
嗯，用户需要知道这个信息，另一个是将来可能有需求支持erc20
