### ISSUE TITLE
无法处理只有一行数据的 csv 文件

### ISSUE THREAD

**Issue by Pana** [conflux-fans/TokenBatchSender#7]
如果使用只有一行的 CSV 文件，页面无响应，console 报错。
[bulk-send.csv](https://github.com/conflux-fans/TokenBatchSender/files/6512459/bulk-send.csv)

如果文件的第一行为标题：address，amount 也不支持。
可以考虑在页面添加详细的描述：不需要添加标题行；或者添加自动检查

**Comment by Pana** [comment]
使用下载的示例 csv 文件，转账 cfx 报如下错误 
<img width="665" alt="Screen Shot 2021-05-20 at 10 34 06 AM" src="https://user-images.githubusercontent.com/552081/118910442-0610f500-b957-11eb-999c-70ed0e7c2e78.png">

**Comment by wangdayong228** [comment]
或者没有选择代币时`转账`按钮不可用

**Comment by wangdayong228** [comment]
> 如果使用只有一行的 CSV 文件，页面无响应，console 报错。
> [bulk-send.csv](https://github.com/conflux-fans/TokenBatchSender/files/6512459/bulk-send.csv)
> 
> 如果文件的第一行为标题：address，amount 也不支持。
> 可以考虑在页面添加详细的描述：不需要添加标题行；或者添加自动检查

判断是否是标题行的条件: 行首非`cfx, cfxtest, net, 0x`

**Comment by darwintree** [comment]
现在兼容了标题行的格式，但要求标题行只能为 address, amount。
不符合该条件将视作没有标题行（即正常地当作address, amount 格式进行解析）

现在没有选择代币时转账按钮被设为了不可用
