### ISSUE TITLE
CFX 转账和代币转账切换放到一个下拉框中 

### ISSUE THREAD

**Issue by Pana** [conflux-fans/TokenBatchSender#8]
<img width="1054" alt="Screen Shot 2021-05-20 at 10 49 50 AM" src="https://user-images.githubusercontent.com/552081/118911723-3fe2fb00-b959-11eb-8240-63e6396e350d.png">

当前 CFX 转账是一个单独的按钮，可以将其跟其他代币放到一个下拉框中，排在首位。
根据选择代币的不同，调用不同的合约和方法。

这样体验更好一些

**Comment by wangdayong228** [comment]
下拉列表当前只需要支持 CFX,FC,CUSDT, 排序顺序也是这样
